### ISSUE TITLE
Assert reports wrong failing command

### ISSUE THREAD

**Issue by thorstenkampe** [bats-core/bats-assert#32]
see below example: bats-core reports that `false` failed (correct) while `assert` reports `true` failed (incorrect).

I suspect that `assert` always reports the previous command as failing while a test can include more than just one `run` and one `assert`.

```bash
load /usr/local/libexec/bats-assert/load.bash
load /usr/local/libexec/bats-support/load.bash

@test core {
    true
    false
}

@test assert {
    true
    assert false
}
```
```
 ✗ core
   (in test file .\mytest.bats, line 8)
     `false' failed
 ✗ assert
   (in test file .\mytest.bats, line 12)
     `true' failed

   -- assertion failed --
   expression : false
   --
```

**Comment by flickerfly** [comment]
false is just a string in bash. A non-empty string is true. Therefore, this is working properly. You need to manage boolean logic differently in your bash. 

Related discussion: 
https://unix.stackexchange.com/questions/105935/understanding-boolean-operators-in-bash-script

**Comment by thorstenkampe** [comment]
@flickerfly quoting from the documentation...
| assert - Fail if the given expression evaluates to false.
...that means the false string is evaluated (to boolean false).

But that was just an example of a failing assertion. The issue is that it reports the `true` statement as failing while it's the assertion that is failing.

**Comment by martin-schulze-vireso** [comment]
@thorstenkampe I can't reproduce this, even with Bats 1.3.0. Please try to provide more detail about your environment and post this at bats-core, since error line reporting comes from over there.
