### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by cornfeedhobo** [bats-core/bats-assert#33]
Can a new release be tagged eventually?

**Comment by polarathene** [comment]
@martin-schulze-vireso are there any issues preventing a tagged release?

It looks like there's been a fair amount of updates since the last one, but I imagine users are more comfortable using tagged releases than pulling git master (_or pinning to an arbitrary commit at the time_).

**Comment by martin-schulze-vireso** [comment]
> @martin-schulze-vireso are there any issues preventing a tagged release?

I'd say mainly lack of time on my part. I am pretty busy with core and see the libraries more as domain of their respective maintainers.

@jasonkarns so you see any reason for not releasing right now?

**Comment by rico-chet** [comment]
@jasonkarns how about a new release, I'd love to use the new regex assertions without pulling in an "intermediate" library version.

**Comment by martin-schulze-vireso** [comment]
I'll get around to that in the next Bats release cycle, so this year.

**Comment by martin-schulze-vireso** [comment]
I just released https://github.com/bats-core/bats-assert/releases/tag/v2.1.0
