### ISSUE TITLE
Test failure due to hard dependency path it test_helper.bash

### ISSUE THREAD

**Issue by flickerfly** [bats-core/bats-assert#34]
When trying to test the bats-assert module, I was getting this error:
`bats: /opt/bats-helpers/bats-assert/test/../node_modules/bats-support/load.bash does not exist`
I resolved it with 
`sed -i 's/node_modules/../g' /opt/bats-helpers/bats-assert/test/test_helper.bash`

This appears to be managed by bats-support and bats-files test_helper.bash scripts with a bit more flexibility that can probably be nearly copy and pasted.

**Comment by martin-schulze-vireso** [comment]
Fixed via #49
