### ISSUE TITLE
[feature] assert_output should --separate-stderr in run

### ISSUE THREAD

**Issue by nicola-lunghi** [bats-core/bats-assert#48]
```bash
@test "ut get_port invalidmachine" {
    # badtestmachine is not in the config
    run --separate-stderr -- get_port "badtestmachine"
    assert_failure
    assert_output "ERROR: Machine 'badtestmachine' is not valid"
}
```
This passes without --separate-stderr
add an option or a command to test also for stderr.
This should apply also to the other assert_ functions.

**Comment by nicola-lunghi** [comment]
maybe add a '--stderr' option to assert_output?

**Comment by martin-schulze-vireso** [comment]
See #42 for a related discussion. If you want to check stderr, you can either not use --separate-stderr or use the workaround in the linked issue.

**Comment by nicola-lunghi** [comment]
Nice! Yes that solve the issue thanks!
