### ISSUE TITLE
Bump npm version to 2.1.0?

### ISSUE THREAD

**Issue by mdwagner** [bats-core/bats-assert#50]
I noticed this new version wasn't published to npm yet.

**Comment by paltherr** [comment]
Same issue for homebrew-bats-assert. It's still on version 2.0.0. The new version 2.1.0 would be very welcome as it includes new features like assert_regex/refute_regex.

**Comment by martin-schulze-vireso** [comment]
So far, only the bats npm package is maintained by this org. You could post your request oer at @jasonkarns' repo.

In the long run we might might offer npm packages under this org.

**Comment by paltherr** [comment]
?!? I don't understand. Isn't https://github.com/bats-core/homebrew-bats-core part of the same org as the one owning https://github.com/bats-core/bats-assert/?

Updating [bats-assert.rb](https://github.com/bats-core/homebrew-bats-core/blob/main/Formula/bats-assert.rb) for the latest version should be as easy as updating the [url](https://github.com/bats-core/homebrew-bats-core/blob/3a18e3d0d59b8b83f5ffb8d6cab1b3ffd21e7dfc/Formula/bats-assert.rb#L4) and the [sha256](https://github.com/bats-core/homebrew-bats-core/blob/3a18e3d0d59b8b83f5ffb8d6cab1b3ffd21e7dfc/Formula/bats-assert.rb#L5). The following patch should do the trick: [patch-upgrade-to-latest-version.txt](https://github.com/bats-core/bats-assert/files/10548707/patch-upgrade-to-latest-version.txt).

If you do that, then anyone using bats-assert via [Homebrew](https://brew.sh/) can simply run "brew update; brew upgrade bats-assert" to get the latest version, which is much easier than manually installing it.

I wonder whether updating the npm package would also be as easy. The npm package is still pointing to version 2.0.0, even though version 2.1.0 was released many months ago. I'm sure npm users too would be very happy to enjoy the latest version.

**Comment by martin-schulze-vireso** [comment]
@paltherr I am sorry, I did not notice you were talking about homebrew. Please open a separate issue in that repository, since the maintainer likely won't see it here. I was only talking about the NPM releases which will require some additional work to automatically generate them during releases. I just wanted to let @mdwagner know that there are currently no official NPM packages besides bats(-core).

**Comment by paltherr** [comment]
OK, I created https://github.com/bats-core/homebrew-bats-core/pull/7.
